import os
import sqlite3
import psycopg
from psycopg import sql

SQLITE_DB = "hardware_inventory.db"
DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set.")

# ======================================================
# DATABASE CONNECTIONS
# ======================================================

sqlite_conn = sqlite3.connect(SQLITE_DB)
sqlite_conn.row_factory = sqlite3.Row

pg_conn = psycopg.connect(DATABASE_URL)
pg_conn.autocommit = False


try:
    pg_cur = pg_conn.cursor()
    sqlite_cur = sqlite_conn.cursor()

    # ======================================================
    # POSTGRESQL TABLE DEFINITIONS
    # Matches the actual SQLite database used by the project
    # ======================================================

    table_definitions = {

        # ==================================================
        # USERS
        # ==================================================

        "users": [
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT UNIQUE NOT NULL",
            "password_hash TEXT NOT NULL",
            "email TEXT UNIQUE NOT NULL",
            "failed_attempts INTEGER DEFAULT 0",
            "locked_until DOUBLE PRECISION DEFAULT 0",
            "role TEXT NOT NULL DEFAULT 'USER'",
            "is_locked INTEGER DEFAULT 0",
        ],

        # ==================================================
        # HARDWARE
        # ==================================================

        "hardware": [
            "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "item_name TEXT NOT NULL",
            "category TEXT NOT NULL",
            "quantity INTEGER NOT NULL",
            "unit_price DOUBLE PRECISION NOT NULL",
            "status TEXT NOT NULL",
            "available_quantity INTEGER",
        ],

        # ==================================================
        # PASSWORD RESET REQUESTS
        # ==================================================

        "password_reset_requests": [
            "request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT NOT NULL",
            "email TEXT NOT NULL",
            "requested_at TEXT NOT NULL",
            "status TEXT NOT NULL DEFAULT 'PENDING'",
            "reviewed_at TEXT",
            "reviewed_by TEXT",
        ],

        # ==================================================
        # BORROW REQUESTS
        # ==================================================

        "borrow_requests": [
            "request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT NOT NULL",
            "item_id BIGINT NOT NULL",
            "quantity INTEGER NOT NULL",
            "purpose TEXT NOT NULL",
            "course TEXT NOT NULL",
            "borrow_date TEXT NOT NULL",
            "expected_return_date TEXT NOT NULL",
            "notes TEXT",
            "status TEXT NOT NULL DEFAULT 'PENDING'",
            "requested_at TEXT NOT NULL",
            "reviewed_at TEXT",
            "reviewed_by TEXT",
            "return_requested_at TEXT",
            "returned_at TEXT",
            "return_confirmed_by TEXT",
            "student_number TEXT",
        ],

        # ==================================================
        # BORROW REQUEST ITEMS
        # ==================================================

        "borrow_request_items": [
            "borrow_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "request_id BIGINT NOT NULL",
            "item_id BIGINT NOT NULL",
            "quantity INTEGER NOT NULL",
        ],
    }

    # ======================================================
    # CREATE POSTGRESQL TABLES
    # ======================================================

    for table_name, columns in table_definitions.items():

        column_sql = sql.SQL(", ").join(
            sql.SQL(column) for column in columns
        )

        create_sql = sql.SQL(
            "CREATE TABLE IF NOT EXISTS {} ({})"
        ).format(
            sql.Identifier(table_name),
            column_sql
        )

        pg_cur.execute(create_sql)

    # ======================================================
    # MIGRATE DATA
    # ======================================================

    counts = {}

    for table_name in table_definitions:

        # Check that destination is empty.
        pg_cur.execute(
            sql.SQL(
                "SELECT COUNT(*) FROM {}"
            ).format(
                sql.Identifier(table_name)
            )
        )

        destination_count = pg_cur.fetchone()[0]

        if destination_count > 0:
            raise RuntimeError(
                f"Destination table '{table_name}' is not empty."
            )

        # SQLite requires a normal SQL string rather than
        # psycopg's SQL composition objects.
        sqlite_cur.execute(
            f'SELECT * FROM "{table_name}"'
        )

        rows = sqlite_cur.fetchall()

        counts[table_name] = len(rows)

        if not rows:
            continue

        source_columns = [
            description[0]
            for description in sqlite_cur.description
        ]

        column_identifiers = sql.SQL(", ").join(
            sql.Identifier(column)
            for column in source_columns
        )

        placeholders = sql.SQL(", ").join(
            sql.Placeholder()
            for _ in source_columns
        )

        insert_sql = sql.SQL(
            "INSERT INTO {} ({}) VALUES ({})"
        ).format(
            sql.Identifier(table_name),
            column_identifiers,
            placeholders
        )

        for row in rows:

            values = [
                row[column]
                for column in source_columns
            ]

            pg_cur.execute(
                insert_sql,
                values
            )

    # ======================================================
    # SYNCHRONIZE POSTGRESQL IDENTITY SEQUENCES
    # ======================================================

    sequence_columns = {
        "users": "id",
        "hardware": "item_id",
        "password_reset_requests": "request_id",
        "borrow_requests": "request_id",
        "borrow_request_items": "borrow_item_id",
    }

    for table_name, id_column in sequence_columns.items():

        # Find the largest migrated ID.
        max_id_sql = sql.SQL(
            "SELECT MAX({}) FROM {}"
        ).format(
            sql.Identifier(id_column),
            sql.Identifier(table_name)
        )

        pg_cur.execute(max_id_sql)

        max_id = pg_cur.fetchone()[0]

        # Only synchronize the sequence when the table
        # contains at least one record.
        if max_id is not None:

            sequence_sql = sql.SQL(
                """
                SELECT setval(
                    pg_get_serial_sequence({}, {}),
                    {},
                    true
                )
                """
            ).format(
                sql.Literal(table_name),
                sql.Literal(id_column),
                sql.Literal(max_id)
            )

            pg_cur.execute(sequence_sql)

    # ======================================================
    # COMMIT MIGRATION
    # ======================================================

    pg_conn.commit()

    print("Migration completed successfully.")
    print(f"  users:                   {counts['users']}")
    print(f"  hardware:                {counts['hardware']}")
    print(
        f"  password_reset_requests: "
        f"{counts['password_reset_requests']}"
    )
    print(
        f"  borrow_requests:         "
        f"{counts['borrow_requests']}"
    )
    print(
        f"  borrow_request_items:    "
        f"{counts['borrow_request_items']}"
    )


except Exception:

    pg_conn.rollback()
    raise


finally:

    sqlite_conn.close()
    pg_conn.close()