import os
import logging
import psycopg


LOG_FOLDER = "app_logging"

os.makedirs(LOG_FOLDER, exist_ok=True)

logging.basicConfig(
    filename=os.path.join(LOG_FOLDER, "app.log"),
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)


# ======================================================
# POSTGRESQL / SUPABASE CONNECTION
# ======================================================

def get_connection():

    database_url = os.getenv("DATABASE_URL")

    if not database_url:
        raise RuntimeError(
            "DATABASE_URL is not set. "
            "Set the Supabase PostgreSQL connection string "
            "before starting the application."
        )

    return psycopg.connect(
        database_url,
        connect_timeout=60,
        sslmode="require"
    )


# ======================================================
# DATABASE INITIALIZATION
# ======================================================

def init_db():

    conn = get_connection()
    cursor = conn.cursor()

    try:

        # --------------------------------------------------
        # USERS
        # --------------------------------------------------

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

                username TEXT UNIQUE NOT NULL,

                password_hash TEXT NOT NULL,

                email TEXT UNIQUE NOT NULL,

                failed_attempts INTEGER DEFAULT 0,

                locked_until DOUBLE PRECISION DEFAULT 0,

                role TEXT NOT NULL DEFAULT 'USER',

                is_locked INTEGER DEFAULT 0
            )
        """)

        # --------------------------------------------------
        # HARDWARE
        # --------------------------------------------------

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS hardware (
                item_id BIGINT GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

                item_name TEXT NOT NULL,

                category TEXT NOT NULL,

                quantity INTEGER NOT NULL,

                unit_price DOUBLE PRECISION NOT NULL,

                status TEXT NOT NULL,

                available_quantity INTEGER
            )
        """)

        # --------------------------------------------------
        # PASSWORD RESET REQUESTS
        # --------------------------------------------------

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS password_reset_requests (
                request_id BIGINT GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

                username TEXT NOT NULL,

                email TEXT NOT NULL,

                requested_at TEXT NOT NULL,

                status TEXT NOT NULL DEFAULT 'PENDING',

                reviewed_at TEXT,

                reviewed_by TEXT
            )
        """)

        # --------------------------------------------------
        # BORROW REQUESTS
        # --------------------------------------------------

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS borrow_requests (
                request_id BIGINT GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

                username TEXT NOT NULL,

                item_id BIGINT NOT NULL,

                quantity INTEGER NOT NULL,

                purpose TEXT NOT NULL,

                course TEXT NOT NULL,

                borrow_date TEXT NOT NULL,

                expected_return_date TEXT NOT NULL,

                notes TEXT,

                status TEXT NOT NULL DEFAULT 'PENDING',

                requested_at TEXT NOT NULL,

                reviewed_at TEXT,

                reviewed_by TEXT,

                return_requested_at TEXT,

                returned_at TEXT,

                return_confirmed_by TEXT,

                student_number TEXT
            )
        """)

        # --------------------------------------------------
        # BORROW REQUEST ITEMS
        # --------------------------------------------------

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS borrow_request_items (
                borrow_item_id BIGINT
                    GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

                request_id BIGINT NOT NULL,

                item_id BIGINT NOT NULL,

                quantity INTEGER NOT NULL
            )
        """)

        # --------------------------------------------------
        # INDEXES
        # --------------------------------------------------

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS
            idx_borrow_requests_username
            ON borrow_requests(username)
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS
            idx_borrow_requests_status
            ON borrow_requests(status)
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS
            idx_borrow_request_items_request
            ON borrow_request_items(request_id)
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS
            idx_borrow_request_items_item
            ON borrow_request_items(item_id)
        """)

        # --------------------------------------------------
        # FIX OLD USER ROLES
        # --------------------------------------------------

        cursor.execute("""
            UPDATE users
            SET role = 'USER'
            WHERE role IS NULL
            OR role = ''
        """)

        conn.commit()

        logging.info(
            "Supabase PostgreSQL database initialized successfully."
        )

    except Exception:

        conn.rollback()

        logging.exception(
            "PostgreSQL database initialization failed."
        )

        raise

    finally:

        cursor.close()
        conn.close()